import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rookas Facebook App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.facebook.com/images/fb_icon_325x325.png" />
      </Head>

        <h1>Facebook in here</h1>

    </div>
  )
}
