import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import {getSession} from "next-auth/client";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import {db} from "../firebase";

export default function Home({ session, posts }) {
  // console.log(session)
  // if() return <Login />;

  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Rookas Facebook App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.facebook.com/images/fb_icon_325x325.png" />
      </Head>

        <Header />
        <main className="flex">
          <Sidebar />
          <Feed posts={posts} />
        {/*    Sidebar */}
        {/*    Feed*/}
        {/*    Widgets*/}
          <Widgets />
        </main>
    </div>
  )
}


export async function getServerSideProps(context) {
  // server side rendering shit goes in here
  const session = await getSession(context);

  // prefetching the posts
  const posts = await db.collection('posts').orderBy('timestamp', 'desc').get();

  const docs = posts.docs.map(post => ({
    id: post.id,
    // the rest ofit
    ...post.data(),
    timestamp: null,
  }))

  // passing back the detials about the login
  return {
    props: {
      session: session,
      // posts are prefetched before user enters the website
      posts: docs,
    }
  }
}